name: testing
on:
  push:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: get-version
        id: version
        run: echo "STEP 1"
        run: Start-Process "www.outlier.cl"
      - uses: actions/checkout@v2
